sudo: required
services:
        - docker
env:
        global:
                - sha=$(git rev-parse HEAD)
                - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
        - curl https://sdk.cloud.google.com | bash > /dev/null;
        - openssl aes-256-cbc -K $encrypted_0e718fcdeb51_key -iv $encrypted_0e718fcdeb51_iv -in gcp.json.enc -out gcp.json -d
        - source $HOME/google-cloud-sdk/path.bash.inc
        - gcloud components update kubectl
        - gcloud auth activate-service-account --key-file gcp.json
        - gcloud config set project multi-k8s-351410
        - gcloud config set compute/zone asia-south2-a
        - gcloud container clusters get-credentials multi-cluster
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t sahilgulati102/react-test -f ./client/Dockerfile.dev ./client
script:
        - docker run -e CI=true sahilgulati102/react-test npm test
deploy:
        provider: script
        script: chmod +x ./deploy.sh && bash ./deploy.sh
        on:
                branch: main
